name: CI
on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests (or smoke test if none)
        run: |
          if [ -d tests ] || ls -1 test_*.py 2>/dev/null | grep -q .; then
            pip install pytest
            pytest -q
          else
            python cli.py -h >/dev/null
          fi
